apiVersion: apps/v1
kind: Deployment
metadata:
  name: closer-geo-point-api
  namespace: egs-uniride
spec:
  replicas: 1
  selector:
    matchLabels:
      app: closer-geo-point-api
  template:
    metadata:
      labels:
        app: closer-geo-point-api
    spec:
      containers:
      - name: closer-geo-point-api
        image: registry.deti:5000/closergeoapi/closer_geo_point_api:0000
        ports:
          - containerPort: 8040
---
apiVersion: v1
kind: Service
metadata:
  name: closer-geo-point-api
  namespace: egs-uniride
spec:
  ports:
    - protocol: TCP
      port: 8040
      name: closer-geo-point-api-svc-port 
  selector:
    app: closer-geo-point-api
  type: ClusterIP